config/routes.rb
Kidable::Application.routes.draw do

  resources :ratings, only: :update
  devise_for :users 
  resources :places do
    resources :comments
  end
  get "pages/home"

  root 'pages#home'
  get 'about' => 'about#about'
  get 'users' => 'users#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "200x200>" }
	has_many :comments
	has_many :ratings
	geocoded_by :address_create

	before_save :scoreme_new
	after_validation :geocode

	scope :san_diego, -> { where("city like ?", "%San Diego%") }

	validates :address, presence: true

	def self.search(search)
		if search
			where("name like ?", "%#{search}%")
		else
			find(:all)
		end
	end

	def average_rating
		Float(self.ratings.sum(:score)) / Float(self.ratings.size)
	end

	def scoreme_new
			kid_menu = self.kid_menu ? 80 : 20

			self.boosters ? boosters = 50 : boosters = 25
			self.high_chairs ? high_chairs = 100 : high_chairs = 5
			self.changing_table ? changing_table = 90 : changing_table = 15
			noise = self.noise_level.to_i * 20
			if self.average_rating.nan?
				place_rating = 25
			elsif self.average_rating == 0.0
				place_rating = 25
			else 
				place_rating = self.average_rating * 40.0
			end
				
			total = kid_menu + boosters + noise + high_chairs + changing_table + place_rating

			score1 = (Float(total)/620.0) * 100
			self.score = score1
	end


	def scoreme
		kid_menu = self.kid_menu ? 80 : 20

		self.boosters ? boosters = 50 : boosters = 25
		self.high_chairs ? high_chairs = 100 : high_chairs = 5
		self.changing_table ? changing_table = 90 : changing_table = 15
		noise = self.noise_level.to_i * 20
		if self.average_rating == 0.0
			rating = 25
		else 
			rating = self.average_rating * 40.0
		end
		total = kid_menu + boosters + noise + high_chairs + changing_table + rating

		score1 = (Float(total)/620.0) * 100 

		self.update_columns(score: score1)


	end

	def address_create
		self.address + ' ' + self.city + ', ' + self.state
	end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	include PlacesHelper

	before_filter :check_admin, only: :edit
	before_filter :set_place, only: [:show, :destroy, :update, :edit, :scoreme]

	def index
			@place = Place.new
			@search_terms = (params[:search].present? ? params[:search] : [])
			@selected_filters = (params[:filter].present? ? params[:filter] : [])
			@selected_types = (params[:filter_types].present? ? params[:filter_types] : [])
			if @selected_types == [] && @search_terms == []
				params[:filter] || params[:filter_types] ? @places = Place.where(city: params[:filter]) : @places = Place.all
			elsif @selected_filters == [] && @search_terms == []
				params[:filter] || params[:filter_types] ? @places = Place.where(place_type: params[:filter_types]) : @places = Place.all
			elsif @search_terms != []
				@places = Place.search(@search_terms)
			else
				params[:filter] || params[:filter_types] ? @places = Place.where(city: params[:filter], place_type: params[:filter_types]) : @places = Place.all
			end

			@hash = Gmaps4rails.build_markers(@places) do |place, marker|
  			marker.lat place.latitude
  			marker.lng place.longitude
  		end
			


	end

	def show
		if @place.ratings != []
			@rating = Rating.where(place_id: @place.id, user_id: current_user.id).first
		else
			@rating = Rating.create(place_id: @place.id, user_id: current_user.id, score: 0)
		end

	end

	def new
		@place = Place.new
	end

	def edit
	end

	def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
	end


	def create
		@place = Place.new(place_params)

		respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
	end

	def city
		@places = Place.where("city like ?", params[:city])
	end




	private

		def check_admin
			redirect_to place_path and return unless current_user.admin?
		end

		def set_place
			@place = Place.find(params[:id])
		end

		def place_params
			params.require(:place).permit(:name, :address, :address2, :city, :state, :zip, :phone, :kid_menu, :high_chairs, :boosters, :approve_kids, :changing_table, :score, :noise_level, :avatar, :place_type)
		end
end

app/helpers/places_helper.rb
module PlacesHelper
	@types = [["Restaurant", "Restaurant"], ["Hotel", "Hotel"], ["Attraction", "Attraction"], ["Park", "Park"]]

	
end

app/views/places/_form.html.erb
<%= simple_form_for @place, html: { class: "horizontal-form"} do |f| %>
<table>

  <tr><td style="width: 200px;"><%= f.input :name, input_html: {style: 'width: 200px'} %></td></tr>
  <tr><td><%= f.input :address, input_html: { style: 'width: 200px'} %></td></tr>
  <tr><td><%= f.input :city, input_html: { style: 'width: 200px'} %></td></tr>
  <tr><td><%= f.input :state, collection: us_states, input_html: { style: 'width: 55px'} %></td><td><%= f.input :zip, input_html: { style: 'width: 100px'} %></td></tr>
  <tr><td><%= f.input :zip, input_html: { style: 'width: 200px'} %></td></tr>

  <tr><td><%= f.input :phone, input_html: { style: 'width: 200px'} %></td></tr>
  <tr><td><%= f.input :kid_menu, as: :boolean %></td></tr>
  <tr><td><%= f.input :score %></td></tr>
  <tr><td><%= f.input :place_type, collection: types %></td></tr>
  <tr><td><%= f.input :avatar, as: :file %></td></tr>
  <tr><td><%= f.button :submit %></td></tr>
</table>
<% end %>

app/views/places/_places.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
		<%= form_for @place, url: { action: "create" }, html: {style: "visibility: none;"} do |f| %>
			
			<%= f.hidden_field :score, value: 0 %>
		  <div class="field form-group">
		  	<%= f.label :name%>
		  	<%= f.text_field :name %>
		  </div>
		  <div class="field form-group">
		  	<%= f.label :address %>
		  	<%= f.text_field :address  %>
		  </div>
	
		  <div class="field form-group">
		  	<%= f.label :city %>
		  	<%= f.text_field :city  %>
		  </div>
		  <div class="field form-group">
		  	<%= f.label :state %>
		  	<%= f.text_field :state  %>
		  </div>
		  <div class="field form-group">
		  	<%= f.label :zip %>
		  	<%= f.text_field :zip  %>
		  </div>

		  <div class="field form-group">
		  	<%= f.label :phone %>
		  	<%= f.text_field :phone  %>
		  </div>
		  <div class="field form-group">
		  	<%= f.label :kid_menu %>
		  	<%= f.check_box :kid_menu  %>
		  </div>
		  <div class="field form-group">
		  	<%= f.label :place_type %>
		  	<%= f.select :place_type, options_for_select([["Restaurant", "Restaurant"], ["Hotel", "Hotel"], ["Attraction", "Attraction"], ["Park", "Park"]])  %>
		  </div>
		  <div class="field form-group">
		  	<%= f.label :avatar %>
		  	<%= f.file_field :avatar %>
		  </div>
		  <br>
		  <div class="actions">
		    <%= f.submit "Save", class: "btn btn-primary" %>
		  </div>
		
		

			</div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
<!--         <button type="button" class="btn btn-primary">Save changes</button> -->
      <!-- </div> --> 
   	</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
	<% end %>

<% @sorted = @places.sort_by { |i| -i.score } %>
<% @sorted.each do |place| %>
	<table class="index" style="margin: auto; width: 550px; ">
		<tr style="border-bottom: 1px solid black;">
			<th class="place_width"><%= link_to place.name, place %><% if current_user.admin? %>     <%= link_to "Edit", edit_place_path(place) %><% end %></th>
			<th>

				<!-- Determines number of stars to display -->
				<% if place.ratings != [] %>
					<% if place.average_rating == 4 %>
						<%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-on.png" %>
					<% elsif place.average_rating == 3 %>
						<%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-on.png" %>
					<% elsif place.average_rating == 5 %>
						<%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-on.png" %>
					<% elsif place.average_rating >= 2.75 && place.average_rating <= 3 %>
						<%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-on.png" %>
					<% elsif place.average_rating > 2.25 && place.average_rating <= 2.74 %>
						<%= image_tag "star-on.png" %><%= image_tag "star-on.png" %><%= image_tag "star-half.png" %>
	
					<% elsif place.average_rating > 1.5 && place.average_rating <= 2 %>
						<%= image_tag "star-on.png" %><%= image_tag "star-on.png" %>
						
					<% elsif place.average_rating <= 1.5 && place.average_rating > 1.00 %>
						<%= image_tag "star-on.png" %><%= image_tag "star-half.png" %>
					<% end %>
				<% end %>

			</th>
			<th style="text-align: right; "><%= place.score.to_i %></th>
		</tr>


		<!-- Table for main body of each place -->
		<table class="tborder" style="margin: auto; width: 550px; margin-top: -1px;">

			<tr style="height: 27px; vertical-align: top;"><td><%= place.place_type %></td></tr>
			<tr class="thover">
				<td style="text-align: left; width: 25%;"><%= image_tag place.avatar.url(:thumb) %></td>
				<td style="width: 75%; vertical-align: top;">
						<table style="width: 100%;">
							<tr>
								<td class="listItems" style="width: 50%; text-align: left;"><%= place.address %></td>
								<td class="listItems" style="width: 10%; text-align: right;">score:</td><td class ="listData" style="width: 40%;"><%= place.score %></td>
							</tr>
							<tr>
								<td class="listItems" style="text-align: left; vertical-align: top;"><%= place.city %>, <%= place.state %> <%= place.zip %></td>
								<td class="listItems" style="text-align: right;">city:</td><td class ="listData" ></td>
							</tr>
							<tr>
								<td class="listItems" style="text-align: left; vertical-align: top;"><%= place.phone %></td>
							</tr>	

						</table>	
				</td>
			</tr>
			
			<!-- Displays last comment on the index list -->
			<tr style="height: 10px;"><td></td></tr>
			<% if place.comments.last != nil %>
					<tr><td colspan="3" style="background-color: rgba(280, 230, 80, .3);"><%= place.comments.last.comment_title %></td></tr>
					<tr><td colspan="3" style="background-color: rgba(280, 230, 80, .3);">"<%= place.comments.last.comment %>"</td></tr>
			<% end %>
		</table>

	</table>
	<br>
	<br>

	
<% end %>     <!-- Each statement close -->


<div style="margin-left: 200px;"><%= debug(params) if Rails.env.development? %></div>

app/views/places/edit.html.erb
<h1>Edit Kid Friendly Place</h1>

<%= render 'form' %>

app/views/places/index.html.erb
<h1 style="margin-left: 193px;">Kid Friendly Places</h1>
<div class="filter">
	<h3>Select City:</h3>
	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

	<%= form_tag places_path, method: 'get', id: "selections" do %>
	<% if @selected_filters == [] %>
		<%= check_box_tag 'filter[]', "San Diego" %>  San Diego<br>
		<%= check_box_tag 'filter[]', "Los Angeles" %>  Los Angeles<br>
		<%= check_box_tag 'filter[]', "Phoenix" %>  Phoenix<br>
	<% else %>
		<% @selected_filters.each do |filter| %>
			<%= check_box_tag 'filter[]', "#{filter}", @selected_filters.include?(filter) %>  <%= filter %><br>

		<% end %>
	<% end %>

	<h3>Select Place Type:</h3>
	<% if @selected_types == [] %>
		<%= check_box_tag 'filter_types[]', "Restaurant" %>  Restaurant<br>
		<%= check_box_tag 'filter_types[]', "Hotel" %>  Hotel<br>
		<%= check_box_tag 'filter_types[]', "Attraction" %>  Attraction<br>
	<% else %>
		<% @selected_types.each do |filtertype| %>
			<%= check_box_tag 'filter_types[]', "Restaurant", @selected_types.include?(filtertype) %>  <%= filtertype %><br>

		<% end %>
	<% end %>
	<br>
		<%= submit_tag 'Submit', class: "btn btn-xs btn-primary", name: nil %>
	<% end %>

	
</div>

<div style="margin-left: 200px;">
	<%= form_tag places_path, method: 'get', id: "places_search",  html: { style: 'width: 200px'} do %>
  	<p>
			<%= text_field_tag :search, params[:search], html: { style: 'width: 200px'} %>
			<%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
			<button class="btn btn-primary btn-sm" style="margin-left: 414px;" data-toggle="modal" data-target="#myModal">
  New Place
	</button>
		</p>
	<% end %>
	
</div>
<div class="map">
	<div id="map" style="width: 250px; height: 250px;"></div>
</div>


<div id="places"><%= render 'places' %></div>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
	});

</script>

app/views/places/index.js.erb
$("#places").html("<%= escape_javascript(render("places")) %>")

app/views/places/new.html.erb
<h1>New Kid Friendly Place</h1>

<%= render 'form' %>

app/views/places/show.html.erb
<%= @place.name %><br>
<%= @place.score %><br>
<% if @place.ratings != [] %>
	<p>Average Rating</p>
<% else %>
	<p>No ratings yet</p>
<% end %>
<div id="star"></div>

<p>Your Rating</p>
<div id="user_star"></div>

<% @place.comments.each do |comment| %>
	<%= comment.comment_title %>, <%= comment.comment %><br>
<% end %>
<%= link_to "New Comment", new_place_comment_path(@place) %>

<script type='text/javascript'>
	$(document).ready(function() {
		setupPlace(<%= @place.average_rating %>, <%= @rating.score %>, <%= @rating.id %>);
	});

</script>